Db helper
ponomareva1/QRcodes_server pull request #1
Opened 2018-12-09 20:05 UTC by veronikaKochugova

2018-12-09 20:31 UTC, veronikaKochugova commented
Возможно, стоит дополнить класс хэлпера методами для создания БД. Тогла в случае, если кто-то первый раз поднимает сервер, то он может создать БД локально. (В том числе тебе не придется самой запускать скрипты создания таблиц)

2018-12-10 10:57 UTC, ponomareva1 commented
@veronikaKochugova  Не получилось создать новую БД:(
Вывод после запуска скрипта /db/test.py:
```
<INFO>: Attempt to create a new database:
pq://postgres:@localhost:5432/QrCodesDB
CONNECTION ERROR
```
И вообще, я не нашла инфы о том, как создать ее, используя py-postgresql, только psycopg2

2018-12-10 12:01 UTC, veronikaKochugova commented
> @veronikaKochugova Не получилось создать новую БД:(
> Вывод после запуска скрипта /db/test.py:
> 
> ```
> <INFO>: Attempt to create a new database:
> pq://postgres:@localhost:5432/QrCodesDB
> CONNECTION ERROR
> ```
> И вообще, я не нашла инфы о том, как создать ее, используя py-postgresql, только psycopg2

Просто обычным запросом создается CREATE DATABASE
А у тебя пострегресс поднят?

2018-12-10 12:05 UTC, ponomareva1 commented
@veronikaKochugova да, поднят
только он фейлится на [этой](https://github.com/ponomareva1/ExpensesAdvisor_server/pull/1/files#diff-d073a5e2f1ed20521ff1a2141b13ec76R141) строчке

2018-12-10 12:19 UTC, veronikaKochugova commented
> @veronikaKochugova да, поднят
> только он фейлится на [этой](https://github.com/ponomareva1/ExpensesAdvisor_server/pull/1/files#diff-d073a5e2f1ed20521ff1a2141b13ec76R141) строчке

У меня не фейлится, видимо, потому что у меня еще и юзер создан, а у тебя его нет... Я попробую добавить строчку, которая перед созданием БД еще и юзера создает
А ты можешь попробовать в консоли зайти под стандартным юзером 

> Создание Вашей первой базы данных
Становимся пользователем postgres (пользователь postgres не имеет пароля по умолчанию, поэтому таким вот образом)
$ sudo su - postgres

2018-12-10 12:22 UTC, muzzy404 requested changes

2018-12-10 12:22 UTC, muzzy404 commented on db/DBHelper.py
> +CHECKS_TABLE = "\"Checks\""
Почему эти константы не классе хелпера или не в отдельном классе? Не очень хорошо, что они просто болтаются, как глобальные переменные.

2018-12-10 12:22 UTC, muzzy404 commented on db/DBHelper.py
> +    def __init__(self, local=True, user="", password="", host="", port="", db_name=""):
Зачем пустые значения по умолчанию?

2018-12-10 12:22 UTC, muzzy404 commented on tests/DBHelperTest.py
> +        delete_user_query = """DELETE FROM "Users" WHERE login = '%s'""" % user_tmp  # cascade deleting
Почему где-то snake_case, а где-то camelCase? Наверное должно быть везде одинаково. Лучше если везде будет snake.

2018-12-10 12:22 UTC, muzzy404 commented on db/DBHelper.py
> +        return pg.open('pq://' + user + ':' + password + '@' + host + ':' + port + '/' + db_name)
Может быть хранить юзера, пароль и т.д. в полях класса, чтобы не передавать их каждый раз для соединения?

2018-12-10 12:22 UTC, muzzy404 commented on db/DBHelper.py
> +    def __create_new_db(self):
snake_case и camelCase, оставить что-то одно, чтобы везде одинаково было

2018-12-10 12:22 UTC, muzzy404 commented on db/DBHelper.py
> +        query = """SELECT CASE WHEN EXISTS (
Думаю, лучше вынести такие строки в константы.

2018-12-10 12:24 UTC, veronikaKochugova commented on db/DBHelper.py
> +CHECKS_TABLE = "\"Checks\""
А я не знаю, как в Питоне правильно констаны заводить. Ты предлагаешь их в поля поместить?

2018-12-10 12:26 UTC, veronikaKochugova commented on db/DBHelper.py
> +    def __init__(self, local=True, user="", password="", host="", port="", db_name=""):
Можно без них и тогда мы будем коннектиться к локальной БД, а можно в дальнейшем их использовать, если подключаться удаленно

2018-12-10 12:26 UTC, veronikaKochugova commented on tests/DBHelperTest.py
> +        delete_user_query = """DELETE FROM "Users" WHERE login = '%s'""" % user_tmp  # cascade deleting
Да, я знаю, просто я еще не доделала. Я Алене говорила. что еще в процессе
Я сначала писала, как привыкла, а потом прочитала, что в Питоне лучше юзать snake_case и старый код еще не рефакторила

2018-12-10 12:28 UTC, veronikaKochugova commented on db/DBHelper.py
> +    def __create_new_db(self):
я знаю....

2018-12-10 14:22 UTC, ponomareva1 requested changes
Как мы договорились: обновить скрипты создания и проверить их выполнимость

2018-12-10 14:22 UTC, ponomareva1 commented on db/DBHelper.py
> +                    self.db = self.__create_new_db()
```suggestion
                    self.__create_new_db()
```
функция `__create_new_db` не возвращает ничего

2018-12-10 14:22 UTC, ponomareva1 commented on db/DBHelper.py
> +            print("CONNECTION ERROR")
минимально - добавить логгирование ошибок, а лучше писать более менее информативный лог во время любых операций с БД

2018-12-10 14:22 UTC, ponomareva1 commented on db/DBHelper.py
> +        values = "('" + login + "','" + password + "')"
```suggestion
        values = "('{login}','{password}')".format(login=login, password=password)
```
ИМХО, так выглядит лучше, и я бы вообще все форматированные строки сделала в ["New Style"](https://realpython.com/python-string-formatting/#2-new-style-string-formatting-strformat)

2018-12-10 14:22 UTC, ponomareva1 commented on db/DBHelper.py
> +                    ELSE False END""" % (USERS_TABLE, login)
Здесь ["New Style"](https://realpython.com/python-string-formatting/#2-new-style-string-formatting-strformat) точно необходим.
```
query = """
SELECT CASE WHEN EXISTS (
                SELECT *
                FROM {table}
                WHERE login = '{login}'
        )
        THEN True
        ELSE False END""".format(table=USERS_TABLE, login=login)
```

2018-12-10 14:22 UTC, ponomareva1 commented on db/DBHelper.py
> +    def addCheck(self, specifier, shop, date, login):
```suggestion
    def addCheck(self, specifier, shop, date, user_login):
```
небольшое уточнение, в слующих функция так же

2018-12-10 14:22 UTC, ponomareva1 commented on db/date/ItemInfo.py
> +class ItemInfo:
почему подобный класс есть только для Item?

2018-12-15 11:39 UTC, veronikaKochugova commented on db/DBHelper.py
> +        values = "('" + login + "','" + password + "')"
первый раз такой способ вижу

2018-12-17 21:24 UTC, ponomareva1 approved these changes

2018-12-17 21:25 UTC, merged